version: 1.0.{build}
configuration: Release

build_script:
- echo hello gAccelerator


after_build:
- cmd: if defined GIT_REPO (git clone --recursive %GIT_REPO% GIT_REPO)
- cmd: if defined GIT_REPO (7z a GIT_REPO.7z GIT_REPO)
- cmd: if defined HG_REPO (hg clone %HG_REPO% HG_REPO)
- cmd: if defined HG_REPO (7z a HG_REPO.7z HG_REPO)
- cmd: if defined CURL_BIN (curl -o CURL_BIN %CURL_BIN% )
#- cmd: if defined YTDL (curl -o youtube-dl.exe https://yt-dl.org/latest/youtube-dl.exe)
- cmd: if defined YTDL (mkdir YTDL)
- cmd: if defined YTDL (cd YTDL)
- cmd: if defined YTDL (pip install --upgrade youtube-dl)
#- cmd: if defined YTDL (..\youtube-dl.exe %YTDL%)
- cmd: if defined YTDL (youtube-dl %YTDL%)
- cmd: if defined YTDL (cd ..)
- cmd: if defined YTDL (7z a YTDL.7z YTDL)
artifacts:
- path: .\GIT_REPO.7z
- path: .\HG_REPO.7z
- path: .\CURL_BIN
- path: .\YTDL.7z
