version: 1.0.{build}
configuration: Release

build:
  project: .\00.sln
  parallel: true
  verbosity: quiet
after_build:
- cmd: if defined THE_REPO (git clone %THE_REPO% THE_REPO)
- cmd: if defined THE_REPO (7z a THE_REPO.7z THE_REPO)
- cmd: if defined THE_URL (curl -o CURL.OUT.FILE.bin %THE_URL% )
artifacts:
- path: .\THE_REPO.7z
- path: .\CURL.OUT.FILE.bin

